version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      symfony:
        patterns:
          - "symfony/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
